# Generated by Django 4.2.10 on 2024-03-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_shop_image_alter_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
    ]
