# Generated by Django 4.2.10 on 2024-03-25 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_order_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_rider': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
