# Generated by Django 4.2.10 on 2024-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
