# Generated by Django 4.2.10 on 2024-03-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_user_acc_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
