# Generated by Django 4.2.10 on 2024-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rider',
            field=models.BooleanField(default=False),
        ),
    ]
